database:
  bulk_insert_size: 1000
  connection_timeout: 30
  verify_data: true
display:
  color_scheme: default
  mode: auto
  refresh_rate: 10
  show_performance: false
downloads:
  chunk_size_hours: 6
  default_days: 7
  delay_between_chunks: 0.1
  max_retries: 3
  parallel_downloads: false
keyboard:
  enabled: true
  navigation_keys: true
  shortcuts: true
logging:
  backup_count: 3
  file: rithmic_admin.log
  level: INFO
  max_size_mb: 10
rithmic:
  connection_timeout: 30
  default_exchange: CME
  heartbeat_interval: 15
  preferred_symbols:
  - NQ
  - ES
  - YM
  - RTY
  retry_attempts: 3
