database:
  host: localhost
  port: 5432
  name: trading_db
  user: trading_user
  password: myData4Tr4ding42user

rithmic:
  system_name: Rithmic Paper Trading
  user: ETF-177266
  password: t2bRVPUaw
  exchange: CME

trading:
  instruments:
    - NQ
    - ES
  timeframes:
    - 1s
    - 1m
    - 5m
    - 15m
    - 4h

models:
  direction_prediction:
    lookback_minutes: 60
    prediction_horizon: 10
  pip_movement:
    target_pips: 40
    timeframe_minutes: 5

logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
