# Layer 1 specific configuration
data_collection:
  start_date: "2023-01-01"
  end_date: "2024-12-31"
  instruments: ["NQ", "ES"]
  
model_training:
  train_split: 0.8
  validation_split: 0.1
  test_split: 0.1
  
backtesting:
  initial_capital: 100000
  commission_per_trade: 2.50
